// src/frontend/Square.tsx
import Piece from "../backend/piece";

interface SquareProps {
	piece: Piece;
	row: number;
	column: number;
	select: (piece: { square: number; piece: Piece }) => void;
}

export default function Square({ row, column, piece, select }: SquareProps) {
	return (
		// biome-ignore lint/a11y/useKeyWithClickEvents: vai ser estranho usar com teclado
		<span
			className={`square ${
				(row + column) % 2 === 0 ? "even" : "odd"
			} row-${row} column-${column} piece-${piece}`}
			onClick={() => select({ square: row * 8 + column, piece })}
		/>
	);
}

// src/frontend/Square.vue
<script setup lang="ts">
import Piece from "../backend/piece";
import gameStore from "./gameStore";

defineProps<{
  piece: Piece
  row: number
  column: number
}>()
</script>


<template>
  <span class="square" :class="[{ even: (row + column) % 2 === 0, odd: (row + column) % 2 === 1 }, `piece-${piece}`]"
    @click="gameStore.select({ square: row * 8 + column, piece })" />
</template>
